### ISSUE TITLE
Reaction color of names

### ISSUE THREAD

**Issue by Dupssky** [Slothpala/HealthBarColor#15]
I love the addon! Any chance you'd be willing to make an option for Classic version to show Name colors depending on reaction type?

![image](https://github.com/user-attachments/assets/7d231128-db86-4de0-a754-57ee38263861)

**Comment by Slothpala** [comment]
Hey this is already possible! You have to enable the Font module, select the unit, in your case this would be Target and change the dropdown of color name to Reaction.
