### ISSUE TITLE
WoW Cataclysm - Resouce Text not formatting with config

### ISSUE THREAD

**Issue by iansardinha** [Slothpala/HealthBarColor#7]
The Resource text (on target and focus) are not formatting properly:
![image](https://github.com/Slothpala/HealthBarColor/assets/110930483/c61b83c4-c978-4b90-b0e9-9e5165402b8d)

**Comment by Slothpala** [comment]
#54a08ce

**Comment by Slothpala** [comment]
Fixed in 54a08ce9d9e38ed21dc9f7650ac9866f05d91f95
