### ISSUE TITLE
Lua Errors

### ISSUE THREAD

**Issue by wheatbread** [Slothpala/HealthBarColor#8]
**Describe the bug**
Hi, I've been getting 15 errors when I log in with 3.2.3 on Dragonflight retail:

https://pastebin.com/NXYtYkUE

**To Reproduce**
1. Log in with 3.2.3 on retail with no other addons

**Expected behavior**

**Have you disabled all other add-ons?**
Yes

**Screenshots**

**Game Version**
Retail

**Additional context**

**Comment by Slothpala** [comment]
Please include the version number you are using. I assume you are using the latest beta version, which should only work on the beta.

**Comment by wheatbread** [comment]
Oh, you're right!   I had set Wowup to install the alpha version.  Setting it back to stable fixed it.

Thank you, and sorry for the bother!

**Comment by Slothpala** [comment]
No worries! Have fun gaming.
